version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - "5672:5672"
            - "15672:15672"
    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - "9000:9000" # MinIO API
            - "9001:9001" # MinIO Console
        environment:
            MINIO_ROOT_USER: admin # Admin username
            MINIO_ROOT_PASSWORD: admin123 # Admin password
        volumes:
            - minio-data:/data # Persistent storage for bucket data
            - minio-config:/root/.minio # Persistent storage for MinIO configuration
        command: server /data --console-address ":9001"

networks:
    default:
        driver: bridge
volumes:
    minio-data:
    minio-config:
