version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - "5672:5672"
            - "15672:15672"

    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - "9000:9000" # MinIO API
            - "9001:9001" # MinIO Console
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: admin123
        volumes:
            - minio-data:/data
            - minio-config:/root/.minio
        command: server /data --console-address ":9001"

    shlink:
        image: shlinkio/shlink:stable
        container_name: shlink
        environment:
            DEFAULT_DOMAIN: localhost:8080
            SHORT_DOMAIN_HOST: localhost:8080
            IS_HTTPS_ENABLED: false
            DB_DRIVER: sqlite
        ports:
            - "8080:8080"
        volumes:
            - shlink-data:/etc/shlink/data

volumes:
    minio-data:
    minio-config:
    shlink-data:


networks:
    default:
        driver: bridge
